spring.application.name=pc_backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/book_my_hotel
spring.datasource.username=postgres
spring.datasource.password=Mohawwal@15

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=awwalmuadshir@gmail.com
spring.mail.password=fexcttbscwmbunhm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=true

app.email=awwalmudashir@gmail.com
app.allowed.origins=http://localhost:3000

jwt.secret=B00K._MyH.t3l_c0M
jwt.expiration=900000

# Future change for flyway
#spring.jpa.hibernate.ddl-auto=validate
#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration

resend.api.key=re_a5mVSUFY_15yAdUzHxwUGb2wWWW9opjD9
resend.email.from=onboarding@resend.dev