-- Cumulative schema for a brand-new database through V23.
--
-- Flyway applies the latest B-prefixed migration only to new environments, then
-- continues with later V-prefixed migrations (V24 and above). Existing databases
-- that already have migration history ignore this file.

CREATE TABLE hotels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(8) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    star_rating INTEGER,
    logo_url VARCHAR(255),
    long_image TEXT
);

CREATE TABLE branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(8) NOT NULL UNIQUE,
    hotel_id BIGINT NOT NULL REFERENCES hotels(id),
    city TEXT,
    country TEXT,
    address VARCHAR(255),
    currency VARCHAR(3) NOT NULL,
    name VARCHAR(255),
    check_in_time TIME WITHOUT TIME ZONE,
    check_out_time TIME WITHOUT TIME ZONE,
    eco_certified BOOLEAN NOT NULL DEFAULT FALSE,
    eco_tags JSONB,
    eco_score INTEGER
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    gender VARCHAR(255),
    role VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    managed_hotel_id BIGINT REFERENCES hotels(id),
    is_active CHAR(1),
    eco_points INTEGER NOT NULL DEFAULT 0,
    email_notifications BOOLEAN DEFAULT FALSE,
    google_id VARCHAR(255) UNIQUE,
    CONSTRAINT chk_users_role CHECK (role IN ('CUSTOMER', 'HOTEL_MANAGER', 'ADMIN'))
);

CREATE TABLE room_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(255),
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_ids JSONB DEFAULT '[]'::jsonb,
    room_id VARCHAR(8) NOT NULL UNIQUE,
    branch_id BIGINT NOT NULL REFERENCES branches(id),
    room_type VARCHAR(255),
    description VARCHAR(255),
    max_occupancy INTEGER,
    price_per_night NUMERIC(38,2),
    amenities JSONB,
    images JSONB,
    currency VARCHAR(3),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE promotions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id BIGINT NOT NULL REFERENCES hotels(id),
    code VARCHAR(50) NOT NULL UNIQUE,
    discount_type VARCHAR(50) NOT NULL DEFAULT 'PERCENTAGE',
    discount_value NUMERIC(10,2) NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE NOT NULL,
    max_uses INTEGER,
    times_used INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    min_booking_amount NUMERIC(10,2),
    max_discount_amount NUMERIC(10,2),
    CONSTRAINT chk_promotions_discount_type
        CHECK (discount_type IN ('PERCENTAGE', 'FIXED_AMOUNT'))
);

CREATE TABLE off_season_packages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope VARCHAR(20) NOT NULL,
    hotel_id BIGINT REFERENCES hotels(id),
    branch_id BIGINT REFERENCES branches(id),
    created_by BIGINT REFERENCES users(id),
    code VARCHAR(40) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    summary VARCHAR(280) NOT NULL,
    description VARCHAR(2000),
    inclusions JSONB NOT NULL DEFAULT '[]'::jsonb,
    eligible_room_types JSONB NOT NULL DEFAULT '[]'::jsonb,
    terms_and_conditions VARCHAR(2500),
    image_url VARCHAR(1000),
    discount_type VARCHAR(30) NOT NULL,
    discount_value NUMERIC(12,2) NOT NULL,
    discount_currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    max_discount_amount NUMERIC(12,2),
    minimum_room_subtotal NUMERIC(12,2),
    booking_start_date DATE NOT NULL,
    booking_end_date DATE NOT NULL,
    stay_start_date DATE NOT NULL,
    stay_end_date DATE NOT NULL,
    minimum_nights INTEGER NOT NULL DEFAULT 1,
    maximum_nights INTEGER,
    minimum_advance_days INTEGER NOT NULL DEFAULT 0,
    max_bookings INTEGER,
    times_booked INTEGER NOT NULL DEFAULT 0,
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_package_scope CHECK (
        (scope = 'GLOBAL' AND hotel_id IS NULL AND branch_id IS NULL) OR
        (scope = 'HOTEL' AND hotel_id IS NOT NULL AND branch_id IS NULL) OR
        (scope = 'BRANCH' AND hotel_id IS NOT NULL AND branch_id IS NOT NULL)
    ),
    CONSTRAINT chk_package_discount_type
        CHECK (discount_type IN ('PERCENTAGE', 'FIXED_AMOUNT')),
    CONSTRAINT chk_package_discount_positive CHECK (discount_value > 0),
    CONSTRAINT chk_package_booking_dates CHECK (booking_end_date >= booking_start_date),
    CONSTRAINT chk_package_stay_dates CHECK (stay_end_date > stay_start_date),
    CONSTRAINT chk_package_nights CHECK (
        minimum_nights >= 1 AND (maximum_nights IS NULL OR maximum_nights >= minimum_nights)
    ),
    CONSTRAINT chk_package_advance_days CHECK (minimum_advance_days >= 0),
    CONSTRAINT chk_package_usage CHECK (
        times_booked >= 0 AND (max_bookings IS NULL OR max_bookings > 0)
    )
);

CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    reference VARCHAR(255),
    room_id BIGINT NOT NULL REFERENCES rooms(id),
    check_in DATE,
    check_out DATE,
    status VARCHAR(255),
    promotion_id BIGINT REFERENCES promotions(id),
    off_season_package_id BIGINT REFERENCES off_season_packages(id) ON DELETE SET NULL,
    package_code VARCHAR(40),
    package_name VARCHAR(120),
    package_discount NUMERIC(12,2) NOT NULL DEFAULT 0,
    total_price NUMERIC(38,2),
    eco_points_earned INTEGER NOT NULL DEFAULT 0,
    eco_points_redeemed INTEGER NOT NULL DEFAULT 0,
    eco_points_discount NUMERIC(12,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT chk_bookings_status
        CHECK (status IS NULL OR status IN ('PENDING', 'CONFIRMED', 'CANCELLED')),
    CONSTRAINT chk_bookings_eco_points_redeemed_non_negative
        CHECK (eco_points_redeemed >= 0),
    CONSTRAINT chk_bookings_eco_points_discount_non_negative
        CHECK (eco_points_discount >= 0)
);

CREATE TABLE services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id BIGINT NOT NULL REFERENCES hotels(id),
    branch_id BIGINT REFERENCES branches(id),
    service_type VARCHAR(255),
    name VARCHAR(255),
    description VARCHAR(255),
    price NUMERIC(38,2),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_services_service_type CHECK (
        service_type IS NULL OR service_type IN (
            'BAR', 'RESTAURANT', 'CAR_HIRE', 'SPA', 'TOUR', 'SERVICE'
        )
    )
);

CREATE TABLE booking_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(id),
    service_id BIGINT NOT NULL REFERENCES services(id),
    service_name VARCHAR(255) NOT NULL,
    unit_price NUMERIC(12,2) NOT NULL,
    quantity INTEGER,
    subtotal NUMERIC(38,2)
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id VARCHAR(8) NOT NULL UNIQUE,
    booking_id BIGINT NOT NULL REFERENCES bookings(id),
    stripe_payment_id VARCHAR(255),
    amount NUMERIC(38,2),
    currency VARCHAR(255),
    status VARCHAR(255),
    refund_id VARCHAR(255),
    paid_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT chk_payments_status CHECK (
        status IS NULL OR status IN ('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED')
    )
);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    branch_id BIGINT NOT NULL REFERENCES branches(id),
    rating INTEGER,
    comment VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    is_verified BOOLEAN
);

CREATE TABLE room_availability (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES rooms(id),
    date DATE,
    reason VARCHAR(255),
    is_available BOOLEAN,
    daily_rate NUMERIC(38,2),
    occupancy_count INTEGER
);

CREATE TABLE room_tags (
    room_id BIGINT NOT NULL REFERENCES rooms(id),
    tag VARCHAR(50) NOT NULL,
    CONSTRAINT uq_room_tags_room_tag UNIQUE (room_id, tag),
    CONSTRAINT chk_room_tags_tag CHECK (tag IN ('ECO_FRIENDLY', 'WORK_FRIENDLY'))
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
    token VARCHAR(255) NOT NULL UNIQUE,
    expiry_date TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE otps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    otp_value VARCHAR(255),
    expiry_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    reset_token VARCHAR(255) UNIQUE
);

CREATE TABLE contact_enquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE promotion_email_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id BIGINT NOT NULL,
    recipient_email TEXT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    processed_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT chk_promotion_notification_status
        CHECK (status IN ('PENDING', 'SENT', 'FAILED'))
);

CREATE TABLE sustainability_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id BIGINT NOT NULL REFERENCES hotels(id),
    branch_id BIGINT REFERENCES branches(id),
    name VARCHAR(80) NOT NULL,
    description VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_bookings_off_season_package
    ON bookings(off_season_package_id);

CREATE INDEX idx_packages_hotel
    ON off_season_packages(hotel_id);

CREATE INDEX idx_packages_branch
    ON off_season_packages(branch_id);

CREATE INDEX idx_packages_public_window
    ON off_season_packages(active, booking_end_date, stay_start_date);

CREATE INDEX idx_promotion_email_notifications_status_attempts
    ON promotion_email_notifications(status, attempts);

CREATE INDEX idx_rooms_is_active
    ON rooms(is_active);

CREATE INDEX idx_services_hotel_active
    ON services(hotel_id, active);

CREATE INDEX idx_services_branch_active
    ON services(branch_id, active);

CREATE INDEX idx_sustainability_tags_hotel
    ON sustainability_tags(hotel_id);

CREATE INDEX idx_sustainability_tags_branch
    ON sustainability_tags(branch_id);

CREATE UNIQUE INDEX uq_active_sustainability_tag_scope_name
    ON sustainability_tags(hotel_id, COALESCE(branch_id, 0), LOWER(name))
    WHERE active = TRUE;
