ALTER TABLE promotions
    ADD COLUMN IF NOT EXISTS hotel_id BIGINT,
    ADD COLUMN IF NOT EXISTS code VARCHAR(50),
    ADD COLUMN IF NOT EXISTS discount_type VARCHAR(50) NOT NULL DEFAULT 'PERCENTAGE',
    ADD COLUMN IF NOT EXISTS discount_value NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS valid_from DATE,
    ADD COLUMN IF NOT EXISTS valid_to DATE,
    ADD COLUMN IF NOT EXISTS max_uses INTEGER,
    ADD COLUMN IF NOT EXISTS times_used INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS min_booking_amount NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS max_discount_amount NUMERIC(10,2);

ALTER TABLE promotions
    ALTER COLUMN discount_type SET DEFAULT 'PERCENTAGE';

ALTER TABLE promotions
    ALTER COLUMN times_used SET DEFAULT 0;

ALTER TABLE promotions
    ALTER COLUMN active SET DEFAULT TRUE;
